name: meditation
description: A new Flutter project.
version: 1.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  carousel_slider: ^4.1.1
  flutter_screenutil: ^5.3.1
  flutter_svg: ^1.1.1+1
  get: ^4.3.8
  flutter:
    sdk: flutter
  url_launcher: ^6.1.5

  cupertino_icons: ^1.0.2
  flutter_cube: ^0.1.1
  model_viewer: ^0.8.1
  animated_splash_screen: ^1.1.0
  lottie: ^1.2.1
  simple_animations: ^4.0.1
  supercharged: ^2.1.1
  font_awesome_flutter: ^9.2.0
  mapbox_gl: ^0.15.0
  flutter_native_splash: ^2.0.2
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.15
  location: ^4.3.0
  dio: ^4.0.4
  flutter_dotenv: ^5.0.2
  localstorage: ^4.0.0+1
  google_fonts: ^3.0.1
  shimmer: ^2.0.0
  firebase_core: ^1.21.1
  firebase_remote_config: ^2.0.16


dev_dependencies:
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path : "assets/images/logo.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icon/
    - assets/image/
    - assets/pics/
    - assets/pics/bgabout.png
    - assets/images/
    - assets/images/Core/
    - assets/3dobjects/
    - assets/3dobjects/Hostelc/
    - assets/3dobjects/Hostele/
    - assets/3dobjects/hostelglb/
    - assets/3dobjects/Hostela/
    - assets/3dobjects/Hostelj/
    - assets/3dobjects/Hostelh/
    - assets/3dobjects/Hostelb/
    - assets/3dobjects/Hostelg/
    - assets/3dobjects/Hosteli/
    - assets/3dobjects/Hostelk/
    - assets/3dobjects/Hostell/
    - assets/3dobjects/Hostelm/
    - assets/3dobjects/Hosteln/
    - assets/3dobjects/Hostelo/
    - assets/3dobjects/Hostelq/
    - assets/3dobjects/Hostelpg/

